language: node_js
sudo: false
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

script:
  - npm install
  # headless chrome add.
  # - ng test
  # - ng e2e
  - npm run ng:build:web

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/SymphoniaApp/
  github_token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: www
